---
- name: Setup reverse proxy sites
  ansible.builtin.template:
    src: reverse_proxy.js
    dest: /etc/caddy/conf.d/{{ site['domain_name'] }}.caddy
    owner: root
    group: root
    mode: 0644
  loop: caddy_sites_reverse_proxy
  loop_control:
    loop_var: site

- name: Reload Caddy service
  ansible.builtin.systemd:
    name: caddy
    state: reloaded
