---
- name: Setup reverse proxy sites
  ansible.builtin.template:
    src: reverse_proxy.j2
    dest: /etc/caddy/conf.d/{{ site['domain_name'] }}.caddy
    owner: root
    group: root
    mode: 0644
  loop: "{{ caddy_sites_reverse_proxy | default([]) }}"
  loop_control:
    loop_var: site

- name: Setup redirect sites
  ansible.builtin.template:
    src: redirect.j2
    dest: /etc/caddy/conf.d/{{ site['domain_name'] }}.caddy
    owner: root
    group: root
    mode: 0644
  loop: "{{ caddy_sites_redirect | default([]) }}"
  loop_control:
    loop_var: site

- name: Reload Caddy service
  ansible.builtin.systemd:
    name: caddy
    state: reloaded
